version: "3.7"
services:
  orchestrator:
    build: 
      context: ./orchestrator
    container_name: orchestrator
    ports:
      - "80:1000"
    volumes:
      - ./orchestrator/app/:/code/app
    environment:
      - DATABASE_URL=postgresql://workshop:workshop@customer-db/workshop_dev
      - BALANCE_URL=http://balance-api:9000
      - BANK_SERVICE=http://integration:4000
  customer-db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=workshop
      - POSTGRES_PASSWORD=workshop
      - POSTGRES_DB=workshop_dev
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    # restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@workshop.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
 
  balance-api:
    build:
      context: ./balance
    container_name: balance-api
    ports:
      - "9000:9000"
    environment:
      - ROCKET_PORT=9000

    depends_on:
      - balance_db
  
  balance_db:
    image: mongo:6.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  integration:
    build:
      context: ./integration
    container_name: integration
    ports:
      - "4000:4000"
volumes:
  postgres_data:
  pgadmin-data:
