version: "3.7"
services:
  # orchester:
  #   build: 
  #     context: ./orchester
  #   container_name: orchester
  #   ports:
  #     - "80:1000"
  #   # restart: always
  #   volumes:
  #     - ./orchester/app/:/code/app
  #   environment:
  #     - DATABASE_URL=postgresql://workshop:workshop@customer-db/workshop_dev
  # customer-db:
  #   image: postgres:12.1-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=workshop
  #     - POSTGRES_PASSWORD=workshop
  #     - POSTGRES_DB=workshop_dev
  #   ports:
  #     - "5432:5432"
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   # restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@workshop.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  balance:
    build:
      context: ./balance
    container_name: balance
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=postgresql://workshop:workshop@customer-db/workshop_dev
      - ROCKET_PORT=9000
    network_mode: 'host'
  balance_db:
    image: mongo
    container_name: balance_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  postgres_data:
  pgadmin-data:
