version: "3.7"
services:
  orchester:
    build: 
      context: ./orchester
    container_name: orchester
    ports:
      - "80:1000"
    # restart: always
    volumes:
      - ./orchester/app/:/code/app
    environment:
      - DATABASE_URL=postgresql://workshop:workshop@customer-db/workshop_dev
      - BALANCE_URL="http://fakeurl/"
  customer-db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=workshop
      - POSTGRES_PASSWORD=workshop
      - POSTGRES_DB=workshop_dev
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    # restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@workshop.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres_data:
  pgadmin-data: