version: "3.7"
services:
  orchestrator:
    build: 
      context: ./orchestrator
    container_name: orchestrator
    ports:
      - "80:1000"
    # restart: always
    volumes:
      - ./orchestrator/app/:/code/app
